### ISSUE TITLE
Rainbond: a paas platform that does not need to know about K8s

### ISSUE THREAD

**Issue by yangkaa** [guettli/open-source-paas#4]
Hello, I'm the maintainer of the open-source project Rainbond. We have developed a PaaS platform that allows developers to deploy applications quickly without needing to understand various Kubernetes concepts. In China, it already has many users, I wish I could add Rainbond to the list.

I believe that some of its features may be helpful to you. eg:

1. Developers don't need to write Dockerfiles or YAML files. You can directly provide your source code repository, and Rainbond will containerize it and run it for you.

2. All operations can be done through a graphical interface. Developers don't need to know Kubernetes concepts like Deployment, Statefulset, Ingress, Service, etc., to manage the full lifecycle of applications, including starting, stopping, updating, and more. You can also perform application maintenance through the web interface.

3. Deployed applications can be easily turned into templates, allowing other users to install them with a single click. All published templates are reusable and can be assembled into new applications.These are just a few of its features. If you're interested, you can learn more.

Github: https://github.com/goodrain/rainbond
Office Website: https://www.rainbond.com/en/

**Comment by guettli** [comment]
I  updated the main text:


Attention: This text is outdated. I work with Kubernetes since one year and like it. Overall it is not that complicated.

The docs at [kubernetes.io](//kubernetes.io) are great.

BTW: The world does not need a wrapper around Kubernetes to simplify it. Just use a managed Kubernetes solution if you don't want to do that yourself.


---

Sorry, closing your PR.
